# Generated by Django 4.0.2 on 2022-03-09 08:43

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('appointmentPlace', models.CharField(choices=[('p1', 'Place 1'), ('p2', 'Place 2')], default='p1', max_length=2)),
                ('appointmentDay', models.DateTimeField()),
                ('personOne', models.CharField(choices=[('p1', 'Person 1'), ('p2', 'Person 2')], default='p1', max_length=2)),
                ('personTwo', models.CharField(choices=[('p1', 'Person 1'), ('p2', 'Person 2')], default='p1', max_length=2)),
                ('type', models.CharField(choices=[('t1', 'Type 1'), ('t2', 'Type 2')], default='t1', max_length=2)),
                ('report', models.TextField()),
            ],
            options={
                'ordering': ['appointmentDay'],
            },
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('surname', models.CharField(blank=True, default='', max_length=100)),
                ('yearsOld', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='path',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('closed', 'Chiuso'), ('ongoing', 'In corso')], default='ongoing', max_length=7)),
                ('authors', djongo.models.fields.ArrayField(model_container=api.models.author)),
                ('appointments', djongo.models.fields.ArrayField(model_container=api.models.appointment)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='woman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('surname', models.CharField(blank=True, default='', max_length=100)),
                ('birthdate', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('citizenship', models.CharField(choices=[('IT', 'Italiana'), ('ST', 'Straniera')], default='IT', max_length=2)),
                ('path', djongo.models.fields.EmbeddedField(model_container=api.models.path)),
                ('report', models.TextField()),
            ],
            options={
                'ordering': ['birthdate'],
            },
        ),
    ]
