# Generated by Django 4.0.2 on 2022-03-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='woman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('surname', models.CharField(blank=True, default='', max_length=100)),
                ('birthdate', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('citizenship', models.CharField(choices=[('IT', 'Italiana'), ('ST', 'Straniera')], default='IT', max_length=2)),
                ('report', models.TextField()),
            ],
            options={
                'ordering': ['birthdate'],
            },
        ),
    ]
